// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/audit.proto

package auditpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	ResponseRef   string                 `protobuf:"bytes,3,opt,name=response_ref,json=responseRef,proto3" json:"response_ref,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // e.g. "SUCCESS", "FAILED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogQueryRequest) Reset() {
	*x = LogQueryRequest{}
	mi := &file_proto_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogQueryRequest) ProtoMessage() {}

func (x *LogQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogQueryRequest.ProtoReflect.Descriptor instead.
func (*LogQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_audit_proto_rawDescGZIP(), []int{0}
}

func (x *LogQueryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *LogQueryRequest) GetResponseRef() string {
	if x != nil {
		return x.ResponseRef
	}
	return ""
}

func (x *LogQueryRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LogQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // UUID of the audit row
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // echo back or normalized status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogQueryResponse) Reset() {
	*x = LogQueryResponse{}
	mi := &file_proto_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogQueryResponse) ProtoMessage() {}

func (x *LogQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogQueryResponse.ProtoReflect.Descriptor instead.
func (*LogQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_audit_proto_rawDescGZIP(), []int{1}
}

func (x *LogQueryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogQueryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_audit_proto protoreflect.FileDescriptor

const file_proto_audit_proto_rawDesc = "" +
	"\n" +
	"\x11proto/audit.proto\x12\x05audit\"{\n" +
	"\x0fLogQueryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12!\n" +
	"\fresponse_ref\x18\x03 \x01(\tR\vresponseRef\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\":\n" +
	"\x10LogQueryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2K\n" +
	"\fAuditService\x12;\n" +
	"\bLogQuery\x12\x16.audit.LogQueryRequest\x1a\x17.audit.LogQueryResponseB7Z5github.com/tyagivivek8/krc-system/audit/proto;auditpbb\x06proto3"

var (
	file_proto_audit_proto_rawDescOnce sync.Once
	file_proto_audit_proto_rawDescData []byte
)

func file_proto_audit_proto_rawDescGZIP() []byte {
	file_proto_audit_proto_rawDescOnce.Do(func() {
		file_proto_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_audit_proto_rawDesc), len(file_proto_audit_proto_rawDesc)))
	})
	return file_proto_audit_proto_rawDescData
}

var file_proto_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_audit_proto_goTypes = []any{
	(*LogQueryRequest)(nil),  // 0: audit.LogQueryRequest
	(*LogQueryResponse)(nil), // 1: audit.LogQueryResponse
}
var file_proto_audit_proto_depIdxs = []int32{
	0, // 0: audit.AuditService.LogQuery:input_type -> audit.LogQueryRequest
	1, // 1: audit.AuditService.LogQuery:output_type -> audit.LogQueryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_audit_proto_init() }
func file_proto_audit_proto_init() {
	if File_proto_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_audit_proto_rawDesc), len(file_proto_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_audit_proto_goTypes,
		DependencyIndexes: file_proto_audit_proto_depIdxs,
		MessageInfos:      file_proto_audit_proto_msgTypes,
	}.Build()
	File_proto_audit_proto = out.File
	file_proto_audit_proto_goTypes = nil
	file_proto_audit_proto_depIdxs = nil
}
